### ISSUE TITLE
Timex.Ecto.DateTime fields and Phoenix.HTML.Form methods

### ISSUE THREAD

**Issue by jerodsanto** [bitwalker/timex_ecto#11]
Loving Timex so far, thanks for the great library!

It would be lovely if Timex DateTime fields would integrate with Phoenix.HTML's form methods (`date_select`, `datetime_select`, `time_select`, and friends).

This appears to need integrations on both sides:
1. When reading the current value of a `Timex.Ecto.DateTime` field for display in the form select
2. When writing the changes to a `Timex.Ecto.DateTime` field

I'm happy to contribute this feature, but I may need a little guidance on the best way to go about it.

(This may be outside the scope of what `timex_ecto` does. I'm open to suggestions in any direction that seems most profitable.)

**Comment by bitwalker** [comment]
Looks like that will need to be implemented as it's own library. I can add that to my TODO list, but if you want to work on such a thing, I'd be glad to provide advice/etc as needed. You could use [phoenix_calendar](https://github.com/lau/phoenix_calendar) as a reference implementation, since it should be almost identical really.

**Comment by 1ternal** [comment]
+1

**Comment by kiliancs** [comment]
@bitwalker I hope @jerodsanto doesn't mind, but I simply needed it working ASAP and decided to give it a try myself.

First I followed your pointer and built https://github.com/Paradem/phoenix_timex inspired by phoenix_calendar, but it became clear that Phoenix.HTML.safe will simply allow us to use Timex in our templates directly (and get rid of the 'protocol Phoenix.HTML.Safe not implemented for...' error). @bitwalker I would appreciate any help with it since now it's including the time ("year-month-day h:min:s") when using a Timex.Ecto.Date struct.

What @jerodsanto seems to be requesting is to allow Ecto to take data from a Phoenix.HTML form and store it in a Timex field in the database. I also gave this a try and ended up with [this PR](https://github.com/bitwalker/timex_ecto/pull/13). I would also appreciate it if @bitwalker could take a look

**Comment by jerodsanto** [comment]
@kiliancs I don't mind at all! I got pulled away to something else and hadn't had a chance to work on this. :+1:

**Comment by bitwalker** [comment]
@kiliancs I've merged your PR, is there anything in particular you'd like me to look at in phoenix_timex?

**Comment by kiliancs** [comment]
Thanks @bitwalker :)
I think it would be great if you could suggest a way to format dates without time information. For example I have a database column with only a date and phoenix_timex formats it including the time information (all zeros).

**Comment by bitwalker** [comment]
@kiliancs Looking at the code, it looks like you are assuming Timex.Date and Timex.Time are structs, but they are not, they are just modules for working with either datetimes or times. The only struct in Timex itself is Timex.DateTime. When you pull a record from Ecto using timex_ecto, you are getting a Timex.DateTime struct out, so defining the protocol for the Timex.Ecto.\* types probably isn't useful.

If you want to format the dates, you have two options the way I see it:
- In your protocol, conditionally check if the time is 00:00:00 UTC, and if so, format it like a date without time.
- Manually format the DateTime struct in your view using DateFormat.format.

Perhaps at some point in the future I'll introduce a Timex.Date struct for working purely on dates, it was a design decision early on to use a unified type to keep the complexity down, and it looks like this might be the one edge case where it's kinda awkward :(.

**Comment by kiliancs** [comment]
Thank you @bitwalker, I updated [PhoenixTimex](https://github.com/Paradem/phoenix_timex) with your recommendations. I will release it as a Hex package in the next few days.

**Comment by bitwalker** [comment]
Right on! I left a comment on your commit, just one thing you may want to consider before publishing.
