### ISSUE TITLE
ecto version constraint collides with phoenix_ecto

### ISSUE THREAD

**Issue by bcardarella** [bitwalker/timex_ecto#2]
You can't have both with the current version constraint. It looks like phoenix_ecto is versioning against ecto's minor version, and this application is versioning against ecto's patch version

**Comment by bitwalker** [comment]
@bcardarella You can specify `{:ecto, "~> x.x.x", override: true}` in your mix.exs to use the version you like. I can probably loosen up the version constraint, but since Ecto is still pre-1.0, I prefer to not blindly allow minor version increments, since they can introduce backwards-incompatible API changes. Right now `timex_ecto` depends on any patch version between `0.12.1` and `0.12.whatever`, if I drop the patch specification, it will allow any minor version up to `1.0.0`.
