### ISSUE TITLE
Does not convert to UTC before storing

### ISSUE THREAD

**Issue by mgwidmann** [bitwalker/timex_ecto#9]
I'm noticing that dates going in as any other timezone other than UTC, come out as UTC but with the hours not adjusted. For example:

``` elixir
# Current date is 11/26/2015 2:53:50 in UTC
%MyApp.Model{
 my_date: %Timex.DateTime{calendar: :gregorian, day: 26, hour: 2,
  minute: 53, month: 11, ms: 904.0, second: 50,
  timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
   full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2015}
  ...
}

# Update the time to a new date in another timezone
MyApp.Model.changeset(model, %{my_date: Timex.Date.now |> Timex.Timezone.convert("America/New_York")}) |> Repo.update

# Returned object from above update as well as refetched object show the following:
# Now in UTC time but hour and day are as if it were in New York timezone
%MyApp.Model{
 my_date: %Timex.DateTime{calendar: :gregorian, day: 25, hour: 21,
  minute: 54, month: 11, ms: 805.0, second: 43,
  timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
   full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2015}
}
```

These two dates are actually within a minute of each other (53:50 vs 54:43) but show as if they are 5 hours apart (New York's difference, -5)

For now, to get things to work right, I have to convert it to UTC prior to putting into the changeset and that fixes my problem.

**Comment by mgwidmann** [comment]
BTW, would be a nice feature to be able to configure the loaded timezone (as it comes out of the DB) on each field, though I can't think of a way to do that with Ecto at the moment.

**Comment by bitwalker** [comment]
@mgwidmann The reason for this is that Ecto assumes everything is UTC in the database, and because you aren't using the `DateTimeWithTimezone` type, `timex-ecto` has no way of knowing what timezone it should actually be when it gets the DateTime, so it defaults to UTC.

In general, you should always store dates/times as UTC, and only convert to a local timezone when necessary, rather than store arbitrary datetime+timezone combinations in your data store. However, if you must store them localized, then you have to take the approach which `DateTimeWithTimezone` does, which is to create a custom type in the database, which stores the datetime+timezone in two columns. If you're using PostgreSQL, the docs cover how to use `DateTimeWithTimezone` so that you can persist localized dates.

**Comment by mgwidmann** [comment]
Can't `timex_ecto` recognize its a non-UTC timezone and convert it for us here: https://github.com/bitwalker/timex_ecto/blob/master/lib/types/datetime.ex#L26

**Comment by bitwalker** [comment]
@mgwidmann Ah I see what you mean, I thought you were talking about when pulling them out of the database. Yes, I can make that change (though not there actually, in the `dump` function instead). I'll get a fix pushed up right away.

**Comment by bitwalker** [comment]
Released in 0.6.0

**Comment by mgwidmann** [comment]
:+1:

**Comment by matteodepalo** [comment]
It seems like here the conversion got removed https://github.com/bitwalker/timex_ecto/commit/92df7c7358aa35739b275c10aa2c47abc4dac889

I'm experiencing this bug again with timex_ecto 3.0.4. Was this code moved somewhere else? I might have lost track of it in the refactor.

**Comment by bitwalker** [comment]
@matteodepalo I pushed a new release to hex with the fix. During the transition I forgot to treat DateTime specially when dumping. Should be good to go now!
